### PR TITLE
Tweak UI to improve look and feel

### PR DESCRIPTION
**Pull request by Cwiiis**
This is the minimal set of changes to (mostly) conform to Eric Pang's initial design tweaks. This doesn't make the suggested layout changes, some of which may not be compatible with OpenHAB's design. Note that this uses CSS variables, which are incompatible with some old browser versions and (currently) Microsoft Edge.

See https://github.com/mozilla/openhab2-addons/pull/2

### CODE REVIEW

**Comment by kdavis-mozilla** [comment]
When you see the GUI changes do you start it using Eclipse or ./start.sh?

**Comment by Cwiiis** [comment]
Using Eclipse.

**Comment by kdavis-mozilla** [comment]
Ok. I'll try there

**Comment by kdavis-mozilla** [comment]
I've tried Eclipse and clean re-build of the distro removing my m2 and I've not seen the GUI changes.

Perhaps there is some flag you've also switched?

**Comment by Cwiiis** [comment]
Yes, you need to enable building of the plugin in the run configuration, or it won't rebuild the jar - I think you put me onto this in the first place though, so you've probably already done that?

**Comment by kdavis-mozilla** [comment]
That was it! There are 4 plugins that contain the word "paper" I only had 3 of them enabled!

**Comment by kdavis-mozilla** [comment]
LGTM!

**Comment by Cwiiis** [comment]
Great! Now get some sleep ;)

**Pull request merged**
