### PR TITLE
Tweak UI to improve look and feel

### PR DESCRIPTION
**Pull request by Cwiiis**
This is the minimal set of changes to (mostly) conform to Eric Pang's initial design tweaks. This doesn't make the suggested layout changes, some of which may not be compatible with OpenHAB's design. Note that this uses CSS variables, which are incompatible with some old browser versions and (currently) Microsoft Edge.

### CODE REVIEW

**Comment by kdavis-mozilla** [comment]
How will upstream changes in org.openhab.ui.paperui be integrated?

They will not cause tests to fail. So, the build system will not flag them,
but the can case the look-and-feel to break.

**Comment by kdavis-mozilla** [comment]
Just saw you make a pull request into [mozilla:master](https://github.com/mozilla/openhab2-addons/tree/master). We should always pull into [mozilla:vaani](https://github.com/mozilla/openhab2-addons/tree/vaani).
Can you make another pull request that targets [mozilla:vaani](https://github.com/mozilla/openhab2-addons/tree/vaani).

**Comment by kdavis-mozilla** [comment]
Maybe I am doing something wrong, but I applied this patch, rebuilt the distro, started up everything, then was presented with the old interface.

I noticed that in the 5 repos there are 5 different files `theme.css` associated with the Paper UI

```
kdaviss-MacBook-Pro:git kdavis$ find . -name theme.css
./openhab-core/bundles/org.openhab.ui.paperui/patch/web/css/theme.css
./openhab2-addons/addons/ui/org.openhab.ui.paperui/patch/web/css/theme.css
./smarthome/extensions/ui/org.eclipse.smarthome.ui.paper/node_modules/bootstrap/docs/examples/theme/theme.css
./smarthome/extensions/ui/org.eclipse.smarthome.ui.paper/web/css/theme.css
./smarthome/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/css/theme.css
```

Is the right one being modified?

**Comment by Cwiiis** [comment]
Re changes - if they change any modified rules, we'll get conflicts and need to resolve them. If they add rules that override existing rules we'll either still get a conflict (because the file is so drastically changed), or it's most likely they're theming something new, and our style works better on top of the OpenHAB one rather than the default anyway.

Re the right files, they are the right files on my machine at least. I have the same files and these changes work - but I needed to make sure the plugin was being rebuilt in the run configuration settings in Eclipse. It does appear that openhab-core and openhab2-addons might conflict, but I assume there's some kind of priority there? (for me, openhab2-addons gets priority)

I'll reopen a pull request on the right branch.

**Comment by kdavis-mozilla** [comment]
When you see the new GUI changes is it using Eclipse or the ./start.sh command?

**Comment by Cwiiis** [comment]
Using Eclipse.

**Pull request closed without merging**
